// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLXvD5yEPlGzAfpe3_BYjo-e3co1yKKvs',
    appId: '1:560131190280:web:cbb5055bf12ebb1865ebbd',
    messagingSenderId: '560131190280',
    projectId: 'fitness-c36e5',
    authDomain: 'fitness-c36e5.firebaseapp.com',
    storageBucket: 'fitness-c36e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6AmSp4EEjiTfKxDwk8nUyg35SoYbhWgo',
    appId: '1:560131190280:android:68d45db9910baeaa65ebbd',
    messagingSenderId: '560131190280',
    projectId: 'fitness-c36e5',
    storageBucket: 'fitness-c36e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj1RpOmFUqqi98zs05ERTszRNi1NTht3E',
    appId: '1:560131190280:ios:8b3d4c44fc572e0665ebbd',
    messagingSenderId: '560131190280',
    projectId: 'fitness-c36e5',
    storageBucket: 'fitness-c36e5.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLXvD5yEPlGzAfpe3_BYjo-e3co1yKKvs',
    appId: '1:560131190280:web:95d8a32712727ba865ebbd',
    messagingSenderId: '560131190280',
    projectId: 'fitness-c36e5',
    authDomain: 'fitness-c36e5.firebaseapp.com',
    storageBucket: 'fitness-c36e5.appspot.com',
  );
}
